version: "3"
services:
  zookeeper:
    container_name: my-zookeeper
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181

  kafka0:
    container_name: my-kafka0
    image: wurstmeister/kafka:2.12-2.3.1
    restart: on-failure
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_VERSION: '2.3.1'
      KAFKA_BROKER_ID: '0'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENERS: 'IN://:9090,OUT://:9092'
      KAFKA_ADVERTISED_LISTENERS: 'IN://kafka0:9090,OUT://localhost:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'IN:PLAINTEXT,OUT:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'IN'
  kafka1:
    container_name: my-kafka1
    image: wurstmeister/kafka:2.12-2.3.1
    restart: on-failure
    depends_on:
      - zookeeper
    ports:
      - 9093:9093
    environment:
      KAFKA_VERSION: '2.3.1'
      KAFKA_BROKER_ID: '1'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENERS: 'IN://:9090,OUT://:9093'
      KAFKA_ADVERTISED_LISTENERS: 'IN://kafka1:9090,OUT://localhost:9093'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'IN:PLAINTEXT,OUT:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'IN'
  kafka2:
    container_name: my-kafka2
    image: wurstmeister/kafka:2.12-2.3.1
    restart: on-failure
    depends_on:
      - zookeeper
    ports:
      - 9094:9094
    environment:
      KAFKA_VERSION: '2.3.1'
      KAFKA_BROKER_ID: '2'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENERS: 'IN://:9090,OUT://:9094'
      KAFKA_ADVERTISED_LISTENERS: 'IN://kafka2:9090,OUT://localhost:9094'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'IN:PLAINTEXT,OUT:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'IN'

networks:
  my-net:
    driver: bridge